# Generated by Django 2.2.3 on 2020-12-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
